# Site settings
title: "Familie Verhaegh"
author: "Matt Verhaegh"
description: "Website over de familie Verhaegh."
keywords: "Software Engineering, Mathematics, Philosophy, Scala, Epistemology, Existentialism, Programming, Machine-Learning, Artificial Intelligence, Statistics, Probability, Puzzles"



colophon: "© MMI — MMXX, Familie Verhaegh"

baseurl: ""
url: "https://www.verhaegh.nl/"


email: webmaster@verhaegh.nl

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
