# Site settings
title: "Familie Verhaegh"
author: "Matt Verhaegh"
description: "Website over de familie Verhaegh."
keywords: "Verhaegh, familie, Helden, Beringe"

colophon: "© MMI — MMXX, Familie Verhaegh"

baseurl: ""
url: "https://www.verhaegh.nl/"


email: webmaster@verhaegh.nl

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
